In [1]:
import numpy as np

(A) Reproducible Normalization Problem

In [2]:
np.random.seed(2112)
X = np.random.randint(10 ,101, size=(5,5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]])

In [3]:
X_normalized = (X-X.mean())/X.std()
print("Normalized X\n",X_normalized)
np.save('X_normalized', X_normalized)

Normalized X
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [4]:
print("Normalized X Mean:" , X_normalized.mean())

Normalized X Mean: 0.0


In [5]:
print("Normalized X Standard Deviation:",X_normalized.std())

Normalized X Standard Deviation: 0.9999999999999999


(B) Cubes Divisible by 4 Problem

In [6]:
C = np.arange(1,101,1)
C = C**3
C.reshape(10,10)
C
div_by_4= C[C%4==0]

print("Cubes Divisible By 4", div_by_4)
np.save('div_by_4', div_by_4)

Cubes Divisible By 4 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


(C) Above-Mean Squares Problem

In [7]:
S = np.arange(1,37,1)
S = S**2
S_mean = S.mean()
above_mean = S[S>S_mean]
print("Squares Above Mean: \n",above_mean)
np.save('above_mean', above_mean)

Squares Above Mean: 
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
